import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/Header'
import { GraphQLClient, gql } from 'graphql-request'
import PlantCard from '../components/PlantCard'

const client = new GraphQLClient('https://directus.shoto.studio/graphql');
const QUERY = gql`
  query {
    plants {
      slug
      title
      price
      amount
      thumbnail {
          id
          title
      }
    }
  }
`;

export async function getStaticProps() {
  const plants = await client.request(QUERY);
  return {
    props: {
      plants: plants.plants,
    },
    revalidate: 10,
  }
}

export default function Home({plants}) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className='container mx-auto py-10 px-2 md:px-0'>
        <section className='grid grid-cols-12 gap-4'>
          {plants.map((plant, index) => (
            <PlantCard key={index} slug={plant.slug} thumbnail={plant.thumbnail} title={plant.title} price={plant.price} amount={plant.amount} />
          ))}
        </section>
      </main>

    </div>
  )
}
